version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Building application...."
      - ./gradlew build
      - echo "Moving binary for execution..."
      - mv build/libs/midas-1.0-SNAPSHOT.jar app.jar
      - aws s3 cp app.jar s3://$DEPLOYMENT_BUCKET

  build:
    commands:
      - echo "creating stack to run job..."
      - aws cloudformation create-stack --stack-name ${JOB_NAME}-${ENVIRONMENT} --template-body file://${CODEBUILD_SRC_DIR}/infrastructure/stacks/application/cloudformation/stack.json --parameters file://${CODEBUILD_SRC_DIR}/infrastructure/stacks/application/cloudformation/environments/${ENVIRONMENT}.json --capabilities CAPABILITY_NAMED_IAM

  post_build:
    commands:
      - echo Deployment completed on `date`
