version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Building application...."
      - ./gradlew build
      - echo "Moving binary for execution..."
      - mv build/libs/midas-1.0-SNAPSHOT.jar app.jar
      - echo "Retrieving core credentials..."
      - aws s3 cp s3://$JOB_BUCKET ./ --recursive
      - chmod -x run-app.sh

  build:
    commands:
      - echo "Running importer...."
      - sh run-app.sh

  post_build:
    commands:
      - echo Build completed on `date`
