version: 0.2

phases:
  #install:
 #   runtime-versions:
 #     java: corretto11

  pre_build:
    commands:
      - yum install -y java-17-amazon-corretto
      - echo $JAVA_HOME
      - #export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - echo "Building application...."
      - ./gradlew build

      - echo "Moving binary for execution..."
      - mv build/libs/midas-1.0-SNAPSHOT.jar app.jar
      - aws s3 cp app.jar s3://${DEPLOYMENT_BUCKET}
      - aws s3 cp src/main/resources/app.conf s3://${DEPLOYMENT_BUCKET}/app.conf
      - aws s3 cp src/main/resources/app.service s3://${DEPLOYMENT_BUCKET}/app.service

  build:
    commands:
      - echo "creating stack to run job..."
      - aws cloudformation create-stack --stack-name ${JOB_NAME}-${ENVIRONMENT} --template-body file://${CODEBUILD_SRC_DIR}/infrastructure/stacks/application/cloudformation/stack.json --parameters ParameterKey=JobName,ParameterValue=$JOB_NAME ParameterKey=Environment,ParameterValue=$ENVIRONMENT ParameterKey=DeploymentBucket,ParameterValue=$DEPLOYMENT_BUCKET ParameterKey=NotificationEmail,ParameterValue=$Notification_Email ParameterKey=ChangeId,ParameterValue=$CODEBUILD_SOURCE_VERSION --capabilities CAPABILITY_NAMED_IAM

  post_build:
    commands:
      - echo Deployment completed on `date`
